name: mtgoupdater-ci

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
      - master
    branches:
      - develop
      - master

env:
  VERBOSE: 1
  BUILD_MODE: Release # For mtgoparser

jobs:
    # JOB to run change detection
  change-detection:
    name: ğŸ” Detect Code Changes before running CI Jobs ğŸ”¬
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      mtgoupdater: ${{ steps.filter.outputs.mtgoupdater }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          mtgoupdater:
            - 'mtgoupdater/**'


  Test:
    # Only run if there's changes to the Rust code (in /mtgoupdater)
    needs: change-detection
    if: ${{ needs.change-detection.outputs.mtgoupdater == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc-13
            generator: "Ninja Multi-Config"
            enable_ipo: On

          - os: macos-13
            compiler: llvm-15.0.3
            generator: "Ninja Multi-Config"
            enable_ipo: Off

          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            enable_ipo: On


    name: âš’ï¸ Build & Test ğŸ“
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy, rustfmt
          bins: cargo-audit
      - name: ğŸ„ Check & Lint MTGO Updater ğŸ©º
        working-directory: ./mtgoupdater
        run: |
          cargo check --verbose
          cargo fmt -- --check
          cargo audit
          cargo doc
          cargo clean
          cargo clippy -- -D warnings --no-deps

      # Now build MTGO Parser and MTGO Getter before running MTGO Updater tests
      #  since the tests validate integration between MTGO Updater and Parser/Getter
      ## Build the MTGO Parser binary
      - name: âš™ï¸ Setup C++ Tools
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ—» Set EXCLUDE_BOOST_LIBS environment variable ğŸï¸
        run: |
          $env:EXCLUDE_BOOST_LIBS = Get-Content -Raw -Path "build-util/boost-exclude-libs.txt"
          Write-Output "EXCLUDE_BOOST_LIBS=$env:EXCLUDE_BOOST_LIBS" >> $env:GITHUB_ENV
        shell: pwsh

      - name: ğŸ”§ Configure CMake
        working-directory: ./mtgoparser
        run: >
          cmake -S .
          -B ./build
          -G "${{matrix.generator}}"
          -Dmtgoparser_ENABLE_IPO=${{matrix.enable_ipo }}
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DGIT_SHA:STRING=${{ github.sha }}
          -DBUILD_TESTING=OFF
          -Dmtgoparser_ENABLE_COVERAGE:BOOL=false
          -Dmtgoparser_PACKAGING_MAINTAINER_MODE:BOOL=OFF
          -Dmtgoparser_WARNINGS_AS_ERRORS:BOOL=OFF
          -Dmtgoparser_ENABLE_CLANG_TIDY:BOOL=OFF
          -Dmtgoparser_ENABLE_CPPCHECK:BOOL=OFF
          -DBOOST_EXCLUDE_LIBRARIES="${{ env.EXCLUDE_BOOST_LIBS }}"
        #run: task mtgoparser:build-for-integration

      - name: Build âš’ï¸ MTGO Parser ğŸ¤“
        working-directory: ./mtgoparser
        run: >
          cmake --build ./build
          --config Release

      ## Build the MTGO Getter binary
      - name: Setup Go ğŸ› ï¸ Toolchain
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build âš’ï¸ MTGO Getter ğŸ¹
        run: task mtgogetter:build

      ## Run the integration tests
      - name: Test ğŸ“ MTGO Updater
        working-directory: ./mtgoupdater
        run: task mtgoupdater:test